In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf
#number 1
custData = {
    'ID': [1, 2, 3],
    'Name:': ['John', 'Bob', 'Stacy']
}
custDf = pd.DataFrame(custData)
print(custDf)

venData = {
    'ID': [5, 6, 7],
    'Name': ['store', 'shop', 'kiosk']
}
venDf = pd.DataFrame(venData)
print(venDf)

purchData = {
    'Customer': ['John', 'Stacy', 'Bob', 'John'],
    'Vendor': ['kiosk', 'store', 'shop', 'shop'],
    'Price': [12, 50, 5, 2]
}
purchDf = pd.DataFrame(purchData)
print(purchDf)









   ID  Name:
0   1   John
1   2    Bob
2   3  Stacy
   ID   Name
0   5  store
1   6   shop
2   7  kiosk
  Customer Vendor  Price
0     John  kiosk     12
1    Stacy  store     50
2      Bob   shop      5
3     John   shop      2


In [ ]:
#number 2
print('highest amount spent')
maxPurchase = purchDf['Price'].idxmax()
print(purchDf.loc[maxPurchase, 'Customer'])





highest amount spent
Stacy


In [ ]:

#number 3
avgPurchases = 0
sum = purchDf.loc[:, 'Price'].sum()
avgPurchases = sum / len(purchDf.index)
print("average purchase price")
print(avgPurchases)



average purchase price
17.25


In [ ]:
#number4
pk = purchDf.groupby('Vendor')
shops = pk.get_group("shop")
kiosk = pk.get_group('kiosk')
store = pk.get_group('store')
Profits = [shops['Price'].sum(), kiosk['Price'].sum(), store['Price'].sum()]
print(Profits)
print("The store made the most money at $50")

[7, 12, 50]
The store made the most money at $50


In [ ]:
#number 5
print('most purchases')
jItems = 0
bItems = 0
sItems = 0
for row in purchDf.iterrows():
    if(row[1]['Customer'] == 'John'):
        jItems+=1
    if (row[1]['Customer'] == 'Bob'):
        bItems += 1
    if (row[1]['Customer'] == 'Stacy'):
        sItems += 1

totals = {jItems:"John",bItems:"Bob",sItems:"Stacy"}
print(totals.get(max(totals)))



most purchases
John


In [ ]:
#number 6
maxPurchase = purchDf['Price'].idxmax()
print('highest single purchase person')
print(purchDf.loc[maxPurchase, 'Customer'])



highest single purchase person
Stacy


In [ ]:
#number 7
df = pd.DataFrame(np.random.randint(1,10,size=(10, 10)))
print(df)



   0  1  2  3  4  5  6  7  8  9
0  6  7  3  7  9  6  1  1  8  6
1  2  8  1  9  6  4  8  1  2  8
2  5  8  3  1  6  1  9  2  2  8
3  4  7  3  1  5  4  9  4  4  5
4  7  3  5  4  9  2  7  5  5  3
5  1  1  2  4  7  5  6  1  8  1
6  2  1  3  8  5  3  7  1  8  5
7  1  4  2  2  6  3  2  6  3  5
8  2  1  2  2  3  1  1  4  8  6
9  7  5  7  5  7  5  6  7  2  3


In [ ]:
#number 8
print(df.min(axis=0))


0    1
1    1
2    1
3    1
4    3
5    1
6    1
7    1
8    2
9    1
dtype: int64


In [ ]:
#number 9
sorted_range = np.sort(df)
print(sorted_range)
f = [0,1,2,3,4,5,6,7,8,9]
for i in f:
  row_number = i
  sum = sorted_range[i,0]+sorted_range[i,1]
  print(f"The sum of the two lowest numbers in row {row_number} is equal to {sum}")

[[1 1 3 6 6 6 7 7 8 9]
 [1 1 2 2 4 6 8 8 8 9]
 [1 1 2 2 3 5 6 8 8 9]
 [1 3 4 4 4 4 5 5 7 9]
 [2 3 3 4 5 5 5 7 7 9]
 [1 1 1 1 2 4 5 6 7 8]
 [1 1 2 3 3 5 5 7 8 8]
 [1 2 2 2 3 3 4 5 6 6]
 [1 1 1 2 2 2 3 4 6 8]
 [2 3 5 5 5 6 7 7 7 7]]
The sum of the two lowest numbers in row 0 is equal to 2
The sum of the two lowest numbers in row 1 is equal to 2
The sum of the two lowest numbers in row 2 is equal to 2
The sum of the two lowest numbers in row 3 is equal to 4
The sum of the two lowest numbers in row 4 is equal to 5
The sum of the two lowest numbers in row 5 is equal to 2
The sum of the two lowest numbers in row 6 is equal to 2
The sum of the two lowest numbers in row 7 is equal to 3
The sum of the two lowest numbers in row 8 is equal to 2
The sum of the two lowest numbers in row 9 is equal to 5


In [ ]:
#number 10
stock_df = yf.download("TSLA",start="2019-01-01",end="2019-12-31")
stock_df['Change_over_day'] = stock_df['Close']-stock_df['Open']
stock_df['percent_change'] = stock_df['Change_over_day']/stock_df['Open']
print(stock_df[stock_df['percent_change']==stock_df['percent_change'].max()])
print("The greatest percent change was on 10-25-2019 of 10.2%")

[*********************100%***********************]  1 of 1 completed
              Open  High        Low      Close  Adj Close     Volume  \
Date                                                                   
2019-10-25  19.848  22.0  19.740667  21.875334  21.875334  450091500   

            Change_over_day  percent_change  
Date                                         
2019-10-25         2.027334        0.102143  
The greatest percent change was on 10-25-2019 of 10.2%


In [ ]:
#number 11
goog_df = yf.download("GOOG",starts="2019-01-01",end="2019-12-31")
goog_df['percent_change'] = (goog_df['Close']-goog_df['Open'])/goog_df['Open']
diff_df = goog_df['percent_change'] - stock_df['percent_change']
diff_df.columns = ['Date','percent_change']
greatest_disp = diff_df.max()
print(greatest_disp*100)

[*********************100%***********************]  1 of 1 completed
6.262862896416572


In [ ]:
pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 62 kB 1.2 MB/s 
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
